@startuml
class BreechMidwife {
    + ExpertHourlyPay : double <<get>>
    + BreechMidwife(fname:string, lname:string, id:string, age:int, hours:double)
    + BreechMidwife(fname:string, lname:string, id:string, age:int)
    + <<override>> EndOfMonthSalary() : double
}
Employee <|-- BreechMidwife
IExpertEmployee <|-- BreechMidwife
@enduml
